
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher

    implementation libs.guava
    implementation libs.mqtt.paho.v5.client
    implementation libs.slf4j.api
    implementation libs.jackson.databind

    implementation libs.commons.cli
    implementation libs.jjwt

    api project(':mqtt-rpc-common')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

tasks.named('test') {
    useJUnitPlatform()
}



def repoBase = findProperty("mavenRepoBaseUrl")
if (!repoBase) throw new GradleException("mavenRepoBaseUrl is not set (project gradle.properties)")

def pubUser = findProperty("mavenUser")
if (!pubUser) throw new GradleException("mavenUser is not set (~/$HOME/gradle.properties)")

def pubPassword = findProperty("mavenPassword")
if (!pubPassword) throw new GradleException("mavenPassword is not set (~/$HOME/gradle.properties)")



publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group.toString()
            artifactId = project.name    // default anyway
            version = project.version.toString()
            from components["java"]
        }
    }

    repositories {
        maven {
            url = uri("${repoBase}/${findProperty('repo') ?: 'snapshots'}")
            credentials {
                username = mavenUser
                password = mavenPassword
            }

            allowInsecureProtocol = true
        }
    }
}


task getDeps(type: Copy) {
  from sourceSets.main.runtimeClasspath, sourceSets.test.runtimeClasspath
  into 'runtime/'
}
